# Generated by Django 2.2.7 on 2019-11-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceStatus', '0002_auto_20191125_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
