# Generated by Django 2.2.7 on 2019-11-26 15:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceStatus', '0003_auto_20191126_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_to', models.PositiveSmallIntegerField(choices=[(1, 'Offline'), (2, 'Online')])),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusactivity', to='DeviceStatus.Device')),
            ],
        ),
    ]
