# Generated by Django 2.2.7 on 2019-11-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceStatus', '0004_statusactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusactivity',
            old_name='changed_at',
            new_name='modified_at',
        ),
    ]
