# Generated by Django 2.2.7 on 2019-11-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceStatus', '0006_remove_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusactivity',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StatusActivity', to='DeviceStatus.Device'),
        ),
    ]
