# Generated by Django 2.2.7 on 2019-11-30 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceStatus', '0007_auto_20191130_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusactivity',
            options={'get_latest_by': 'modified_at'},
        ),
        migrations.AlterField(
            model_name='statusactivity',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_activites', to='DeviceStatus.Device'),
        ),
    ]
