# Generated by Django 2.2.7 on 2019-11-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceStatus', '0008_auto_20191130_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusactivity',
            old_name='changed_to',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='statusactivity',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_activity', to='DeviceStatus.Device'),
        ),
    ]
